# Autogenerated wrapper script for extxyz_jll for x86_64-w64-mingw32
export libextxyz

using PCRE2_jll
using libcleri_jll
JLLWrappers.@generate_wrapper_header("extxyz")
JLLWrappers.@declare_library_product(libextxyz, "libextxyz.dll")
function __init__()
    JLLWrappers.@generate_init_header(PCRE2_jll, libcleri_jll)
    JLLWrappers.@init_library_product(
        libextxyz,
        "bin\\libextxyz.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
